### ISSUE TITLE
java.lang.NullPointerException: it must not be null

### ISSUE THREAD

**Issue by troit5ky** [Kieaer/Essentials#101]
Discord auth error when player joined at server

```java
java.lang.NullPointerException: it must not be null
        at essentials.event.EventThread.run(EventThread.kt:220)
        at essentials.event.Event$register$7.get(Event.kt:37)
        at essentials.event.Event$register$7.get(Event.kt:36)
        at arc.Events.lambda$fire$2(Events.java:30)
        at arc.struct.Seq.each(Seq.java:200)
        at arc.Events.fire(Events.java:30)
        at arc.Events.fire(Events.java:25)
        at mindustry.core.NetServer.connectConfirm(NetServer.java:778)
        at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:144)
        at mindustry.core.NetServer.lambda$new$7(NetServer.java:261)
        at mindustry.net.Net.handleServerReceived(Net.java:277)
        at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:118)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:83)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
```

**Comment by Kieaer** [comment]
Caused by anti vpn file doesn't exist
turn off anti vpn in config file to solve this issue
