### ISSUE TITLE
Invocation Target Exception

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [Kieaer/Essentials#103]
**How to reproduce**
1. aws server
2. wget latest release
3. run the workaround in #102 

**Logs**
```
[E] Failed to load mod file config/mods/Essentials.jar. Skipping.                  
[05-05-2022 05:45:05] [E] java.lang.reflect.InvocationTargetException                                    
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)     
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)      
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)                 
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)                           
        at mindustry.mod.Mods.loadMod(Mods.java:812)                                                     
        at mindustry.mod.Mods.loadMod(Mods.java:714)                                                     
        at mindustry.mod.Mods.load(Mods.java:363)                                                        
        at mindustry.Vars.init(Vars.java:320)                                                            
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:47)                                  
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:65)                
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)                   
Caused by: java.lang.NoSuchFieldError: player                                                            
        at essentials.PluginData.<clinit>(PluginData.kt:32)                                              
        at essentials.Main.<init>(Main.kt:67)                                                            
        ... 12 more
```

**Additional context**

**Comment by Kieaer** [comment]
7.0 version still in development (Anuke keep changing internal structure)
You must check your 7.0 sevrer is last released version.

**Comment by Just-a-Unity-Dev** [comment]
im on latest version v135.2

**Comment by Kieaer** [comment]
Use 6.0 version plugin

**Comment by Kieaer** [comment]
It caused by gradle.
