### ISSUE TITLE
Server crashes on setperm

### ISSUE THREAD

**Issue by Miniontoby** [Kieaer/Essentials#113]
**Logs**
```
setperm Miniontoby owner
[01-24-2023 17:23:23] [E] java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at essentials.Commands$Server.setperm(Commands.kt:1905)
        at essentials.Commands._init_$lambda$53(Commands.kt:125)
        at arc.util.CommandHandler.lambda$register$2(CommandHandler.java:129)
        at arc.util.CommandHandler.handleMessage(CommandHandler.java:86)
        at arc.util.CommandHandler.handleMessage(CommandHandler.java:30)
        at mindustry.server.ServerControl.handleCommandString(ServerControl.java:1005)
        at mindustry.server.ServerControl.lambda$new$0(ServerControl.java:52)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:81)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
```

**Additional context**

**Comment by Kieaer** [comment]
For now, modify permission_user.txt and use it.
