### ISSUE TITLE
DB MySQL

### ISSUE THREAD

**Issue by 44wrw44** [Kieaer/Essentials#123]
How can I use MySQL databases in the plugin, otherwise using the recommended database breaks my servers

**Comment by Kieaer** [comment]
My mistake. no write how to create DB :(
you need create essentials database

execute this SQL to mysql command-line
CREATE DATABASE essentials

**Comment by 44wrw44** [comment]
As a result, I get an error, although everything has been created and I can easily connect to the database.

```
[02-25-2024 06:35:39] [I] [Essentials] Loading
java.sql.SQLException: No suitable driver found for jdbc:mysql://127.0.0.1:3306/essentials
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:708)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
        at org.jetbrains.exposed.sql.Database$Companion$connect$8.invoke(Database.kt:278)
        at org.jetbrains.exposed.sql.Database$Companion$connect$8.invoke(Database.kt:274)
        at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:165)
        at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:166)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:120)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:119)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:145)
        at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt)
        at essentials.DB$open$2.invoke(DB.kt:61)
        at essentials.DB$open$2.invoke(DB.kt:61)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:306)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:353)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:361)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:352)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:261)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:361)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:231)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:209)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:208)
        at essentials.DB.open(DB.kt:61)
        at essentials.Main.<init>(Main.kt:51)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at mindustry.mod.Mods.loadMod(Mods.java:971)
        at mindustry.mod.Mods.load(Mods.java:465)
        at mindustry.Vars.init(Vars.java:337)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:48)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
```

**Comment by 44wrw44** [comment]
![image](https://github.com/Kieaer/Essentials/assets/73754757/8a1a1fb4-ec26-4c0a-82e8-b1ec81ddcaf8)
Shouldn't it change the driver request to com.mysql.jdbc.Driver?

**Comment by Kieaer** [comment]
My bad 😇
I'll fix it within an hour

**Comment by Kieaer** [comment]
https://github.com/Kieaer/Essentials/releases/tag/v19.1

**Comment by 44wrw44** [comment]
![image](https://github.com/Kieaer/Essentials/assets/73754757/dc70fcdc-81c8-4cb7-aa58-191ac999e0dd)
The problem is not solved, now it connects to the local db according to the standard, but the external db is specified in the config.

**Comment by Kieaer** [comment]
@44wrw44 You need give "create" command permission to wrw@192.168.0.111 account.
Use ``GRANT PRIVILEGE ON essentials.* TO 'wrw'@'192.168.0.111'`` command to mysql command line.
And apply permission to use this command - ``FLUSH PRIVILEGES;``

**Comment by 44wrw44** [comment]
He has been issued rights `*.*`

**Comment by Kieaer** [comment]
@44wrw44 Can you upload this command result?
show grants for wrw@'192.168.0.111'

**Comment by 44wrw44** [comment]
![image](https://github.com/Kieaer/Essentials/assets/73754757/1c57f4a8-6d67-4a02-a0f3-bdd720cbefc3)

**Comment by 44wrw44** [comment]
Found a problem, FireWall was blocking access to LAN through an isolated zone

**Comment by Kieaer** [comment]
If you have any other bugs or inquiries, feel free to come 🙂
