### ISSUE TITLE
Not connecting to Mysql Database

### ISSUE THREAD

**Issue by xxcosita3czxx** [Kieaer/Essentials#126]
Im trying to connect it to pterodactyl mysql database, tried giving it ip instead of domain, and essentials is only plugin on the server, the server is clean, running java 21. Using latest version from releases.

Logs:

container@pelican~ java -version
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
container@pelican~ java -Xms128M -Xmx4000M -jar server-release.jar config port 30140,config name A Pterodactyl Hosted Server,host Tendrils
[07-02-2024 15:42:14] [I] [Essentials] Loading
java.sql.SQLException: No database installed or essentials database not created.
        at essentials.DB.getDriverName(DB.kt:54)
        at essentials.DB.open(DB.kt:75)
        at essentials.Main.<init>(Main.kt:51)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at mindustry.mod.Mods.loadMod(Mods.java:971)
        at mindustry.mod.Mods.load(Mods.java:465)
        at mindustry.Vars.init(Vars.java:337)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:48)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by Kieaer** [comment]
Make sure install mysql on local pc
and create database
``CREATE DATABSASE essentials``
run this command from mysql shell

External DB stability is high, but it's too inconvenient.
I will fix this problem when release next version.

**Comment by xxcosita3czxx** [comment]
I cannot create the database on computer, it has to be through the panel

**Comment by Kieaer** [comment]
Use https://github.com/Kieaer/Essentials/releases/tag/v18.2

**Comment by Kieaer** [comment]
https://github.com/Kieaer/Essentials/releases/tag/v20
You need change database path to ``sqlite:essentials.db`` in ``/config/mods/Essentials/config/config.yaml``
