### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by makarasty** [Kieaer/Essentials#134]
Can you compile my corrected version with admin nicknames, it stopped working for me for some reason

My compiled plugin just won't run

**Comment by Kieaer** [comment]
[Essential.zip](https://github.com/user-attachments/files/18087985/Essential.zip)
Here's last build

**Comment by makarasty** [comment]
thank you

**Comment by makarasty** [comment]
I don't understand why, but this version won't run on the host

## Java: `ghcr.io/pterodactyl/yolks:java_21`
```
container@pterodactyl~ java -version
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
```

## Log:
```[12-11-2024 11:00:31] [E] java.lang.RuntimeException: Error loading mod essential
        at mindustry.mod.Mods.contextRun(Mods.java:797)
        at mindustry.mod.Mods.lambda$eachClass$30(Mods.java:785)
        at arc.struct.Seq.each(Seq.java:182)
        at mindustry.mod.Mods.eachClass(Mods.java:785)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:80)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
Caused by: org.jetbrains.exposed.exceptions.ExposedSQLException: java.sql.SQLException: SQL String cannot be empty
SQL: []
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:83)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:292)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:269)
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:59)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.executeInBatch(JdbcConnectionImpl.kt:130)
        at org.jetbrains.exposed.sql.Transaction.execInBatch(Transaction.kt:276)
        at org.jetbrains.exposed.sql.SchemaUtils.execStatements(SchemaUtils.kt:362)
        at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:373)
        at essential.core.DB.createTable$lambda$5(DB.kt:120)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:324)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:371)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:379)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:370)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:279)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:379)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:249)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:227)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:226)
        at essential.core.DB.createTable(DB.kt:119)
        at essential.core.Main.init(Main.kt:103)
        at mindustry.mod.Mods.lambda$eachClass$29(Mods.java:785)
        at mindustry.mod.Mods.contextRun(Mods.java:795)
        ... 6 more
Caused by: java.sql.SQLException: SQL String cannot be empty
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:65)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76)
        at com.mysql.cj.jdbc.ClientPreparedStatement.<init>(ClientPreparedStatement.java:213)
        at com.mysql.cj.jdbc.ClientPreparedStatement.<init>(ClientPreparedStatement.java:187)
        at com.mysql.cj.jdbc.ClientPreparedStatement.getInstance(ClientPreparedStatement.java:128)
        at com.mysql.cj.jdbc.ConnectionImpl.clientPrepareStatement(ConnectionImpl.java:687)
        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1673)
        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1589)
        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1594)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.prepareStatement(JdbcConnectionImpl.kt:80)
        at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:46)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl$executeInBatch$prepStatement$1.prepared(JdbcConnectionImpl.kt:102)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:79)
        ... 28 more
Caused by: com.mysql.cj.exceptions.WrongArgumentException: SQL String cannot be empty
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:76)
        at com.mysql.cj.ClientPreparedQuery.checkNullOrEmptyQuery(ClientPreparedQuery.java:147)
        at com.mysql.cj.jdbc.ClientPreparedStatement.<init>(ClientPreparedStatement.java:209)
        ... 38 more
```
the configuration itself specifies mysql, which is 100% correct as it works with the previous version
        
## clean reinstall log
```
[12-11-2024 11:04:32] [I] Downloading postgresql-42.7.3.jar...
[12-11-2024 11:04:32] [I] postgresql-42.7.3.jar saved
[12-11-2024 11:04:32] [I] Downloading mysql-connector-j-8.4.0.jar...
[12-11-2024 11:04:33] [I] mysql-connector-j-8.4.0.jar saved
[12-11-2024 11:04:33] [I] Downloading mariadb-java-client-3.4.0.jar...
[12-11-2024 11:04:34] [I] mariadb-java-client-3.4.0.jar saved
[12-11-2024 11:04:34] [I] Downloading sqlite-jdbc-3.46.0.0.jar...
[12-11-2024 11:04:34] [I] sqlite-jdbc-3.46.0.0.jar saved
[12-11-2024 11:04:34] [I] Downloading h2-2.2.224.jar...
[12-11-2024 11:04:34] [I] h2-2.2.224.jar saved
[12-11-2024 11:04:34] [I] Downloading mssql-jdbc-12.6.2.jre11.jar...
[12-11-2024 11:04:34] [I] mssql-jdbc-12.6.2.jre11.jar saved
[12-11-2024 11:04:35] [I] [Essential] The current plugin version is the latest version!
[12-11-2024 11:04:35] [E] java.lang.RuntimeException: Error loading mod essential
        at mindustry.mod.Mods.contextRun(Mods.java:797)
        at mindustry.mod.Mods.lambda$eachClass$30(Mods.java:785)
        at arc.struct.Seq.each(Seq.java:182)
        at mindustry.mod.Mods.eachClass(Mods.java:785)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:80)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6d078728[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@14e23d07[Wrapped task = essential.core.Trigger$UpdateThread@1e2f4390]] rejected from java.util.concurrent.ThreadPoolExecutor@1f635fa8[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 0]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
        at essential.core.Main.init(Main.kt:130)
        at mindustry.mod.Mods.lambda$eachClass$29(Mods.java:785)
        at mindustry.mod.Mods.contextRun(Mods.java:795)
        ... 6 more
        ```

**Comment by Kieaer** [comment]
2 thread cpu..? 🤔
Just running the main thread(game logic) and pathfinding thread(unit pathfinding) has no place for the plugin thread

**Comment by makarasty** [comment]
Yes, but no matter how I limit the cores on my Windows computer, everything works perfectly

**Comment by makarasty** [comment]
And the most surprising and interesting thing is that there was no such error in the previous version

**Comment by Kieaer** [comment]
[Essential.zip](https://github.com/user-attachments/files/18104011/Essential.zip)
Here's temporary fix build
It may makes stuck server because thread limit

**Comment by makarasty** [comment]
The first run was successful, but all subsequent attempts result in this error, even when using MySQL and stopping the server with the `exit` command
```
[12-12-2024 11:06:47] [E] java.lang.RuntimeException: Error loading mod essential
        at mindustry.mod.Mods.contextRun(Mods.java:797)
        at mindustry.mod.Mods.lambda$eachClass$30(Mods.java:785)
        at arc.struct.Seq.each(Seq.java:182)
        at mindustry.mod.Mods.eachClass(Mods.java:785)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:80)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
Caused by: org.jetbrains.exposed.exceptions.ExposedSQLException: java.sql.SQLException: SQL String cannot be empty
SQL: []
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:83)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:292)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:269)
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:59)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.executeInBatch(JdbcConnectionImpl.kt:130)
        at org.jetbrains.exposed.sql.Transaction.execInBatch(Transaction.kt:276)
        at org.jetbrains.exposed.sql.SchemaUtils.execStatements(SchemaUtils.kt:362)
        at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:373)
        at essential.core.DB.createTable$lambda$5(DB.kt:120)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:324)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:371)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:379)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:370)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:279)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:379)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:249)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:227)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:226)
        at essential.core.DB.createTable(DB.kt:119)
        at essential.core.Main.init(Main.kt:103)
        at mindustry.mod.Mods.lambda$eachClass$29(Mods.java:785)
        at mindustry.mod.Mods.contextRun(Mods.java:795)
        ... 6 more
Caused by: java.sql.SQLException: SQL String cannot be empty
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:65)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76)
        at com.mysql.cj.jdbc.ClientPreparedStatement.<init>(ClientPreparedStatement.java:213)
        at com.mysql.cj.jdbc.ClientPreparedStatement.<init>(ClientPreparedStatement.java:187)
        at com.mysql.cj.jdbc.ClientPreparedStatement.getInstance(ClientPreparedStatement.java:128)
        at com.mysql.cj.jdbc.ConnectionImpl.clientPrepareStatement(ConnectionImpl.java:687)
        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1673)
        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1589)
        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1594)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.prepareStatement(JdbcConnectionImpl.kt:80)
        at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:46)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl$executeInBatch$prepStatement$1.prepared(JdbcConnectionImpl.kt:102)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:79)
        ... 28 more
Caused by: com.mysql.cj.exceptions.WrongArgumentException: SQL String cannot be empty
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:76)
        at com.mysql.cj.ClientPreparedQuery.checkNullOrEmptyQuery(ClientPreparedQuery.java:147)
        at com.mysql.cj.jdbc.ClientPreparedStatement.<init>(ClientPreparedStatement.java:209)
        ... 38 more
```

**Comment by makarasty** [comment]
After a clean installation and initial launch, everything worked well as you can see, but after restarting using the exit command, the plugin stopped functioning. However, using the release version v20 works correctly if MySQL is used. Why is this happening?
```
[Host] Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -Xmx1024M -jar server-release.jar
[12-12-2024 11:10:25] [I] Time to initialize modded scripts: 214.4144
[12-12-2024 11:10:26] [I] 8 mods loaded.
[12-12-2024 11:10:26] [I] Downloading postgresql-42.7.3.jar...
[12-12-2024 11:10:27] [I] postgresql-42.7.3.jar saved
[12-12-2024 11:10:27] [I] Downloading mysql-connector-j-8.4.0.jar...
[12-12-2024 11:10:28] [I] mysql-connector-j-8.4.0.jar saved
[12-12-2024 11:10:28] [I] Downloading mariadb-java-client-3.4.0.jar...
[12-12-2024 11:10:28] [I] mariadb-java-client-3.4.0.jar saved
[12-12-2024 11:10:28] [I] Downloading sqlite-jdbc-3.46.0.0.jar...
[12-12-2024 11:10:28] [I] sqlite-jdbc-3.46.0.0.jar saved
[12-12-2024 11:10:28] [I] Downloading h2-2.2.224.jar...
[12-12-2024 11:10:28] [I] h2-2.2.224.jar saved
[12-12-2024 11:10:28] [I] Downloading mssql-jdbc-12.6.2.jre11.jar...
[12-12-2024 11:10:28] [I] mssql-jdbc-12.6.2.jre11.jar saved
[12-12-2024 11:10:29] [I] [Essential] The current plugin version is the latest version!
[12-12-2024 11:10:29] [I] [Essential] Loaded.
[12-12-2024 11:10:29] [I] Config file updated!
[12-12-2024 11:10:29] [I] Config file updated!
[12-12-2024 11:10:29] [I] Config file updated!
[12-12-2024 11:10:29] [I] Server loaded. Type 'help' for help.
[Host] Server marked as running...
[12-12-2024 11:10:29] [I] Found 3 command-line arguments to parse.
[12-12-2024 11:10:29] [I] Found 1 startup commands.
[12-12-2024 11:10:29] [I] port set to 27715.
[12-12-2024 11:10:29] [I] Loading map...
[12-12-2024 11:10:30] [I] Map loaded.
[12-12-2024 11:10:30] [I] Opened a server on port 27715.
[12-12-2024 11:10:30] [I] 25 MB collected. Memory usage now at 64 MB.
[Pterodactyl Daemon]: Firewall rules successfully added to the server.
[Host] Server marked as stopping...
exit
[12-12-2024 11:12:34] [I] Shutting down server.
[Host] Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
[Host] Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -Xmx1024M -jar server-release.jar
[12-12-2024 11:12:44] [I] Time to initialize modded scripts: 190.89297
[12-12-2024 11:12:45] [I] 8 mods loaded.
[12-12-2024 11:12:46] [E] java.lang.RuntimeException: Error loading mod essential
        at mindustry.mod.Mods.contextRun(Mods.java:797)
        at mindustry.mod.Mods.lambda$eachClass$30(Mods.java:785)
        at arc.struct.Seq.each(Seq.java:182)
        at mindustry.mod.Mods.eachClass(Mods.java:785)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:80)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
Caused by: org.jetbrains.exposed.exceptions.ExposedSQLException: java.sql.SQLException: The prepared statement has been finalized
SQL: []
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:83)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:292)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:269)
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:59)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.executeInBatch(JdbcConnectionImpl.kt:130)
        at org.jetbrains.exposed.sql.Transaction.execInBatch(Transaction.kt:276)
        at org.jetbrains.exposed.sql.SchemaUtils.execStatements(SchemaUtils.kt:362)
        at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:373)
        at essential.core.DB.createTable$lambda$5(DB.kt:120)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:324)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:371)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:379)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:370)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:279)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:379)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:249)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:227)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:226)
        at essential.core.DB.createTable(DB.kt:119)
        at essential.core.Main.init(Main.kt:103)
        at mindustry.mod.Mods.lambda$eachClass$29(Mods.java:785)
        at mindustry.mod.Mods.contextRun(Mods.java:795)
        ... 6 more
Caused by: java.sql.SQLException: The prepared statement has been finalized
        at org.sqlite.core.NativeDB.throwex(NativeDB.java:500)
        at org.sqlite.core.NativeDB.column_count(Native Method)
        at org.sqlite.core.DB.column_names(DB.java:862)
        at org.sqlite.core.SafeStmtPtr.safeRun(SafeStmtPtr.java:128)
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:225)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:210)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.prepareStatement(JdbcConnectionImpl.kt:80)
        at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:46)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl$executeInBatch$prepStatement$1.prepared(JdbcConnectionImpl.kt:102)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:79)
        ... 28 more

[Host] Server marked as offline...
```

**Comment by Kieaer** [comment]
There's some cause that does not occur on my system.
I'm investigating the bug and will release a hotfix soon.

**Comment by Kieaer** [comment]
Merge to https://github.com/Kieaer/Essentials/issues/132
