### ISSUE TITLE
6.0 v1 not loading

### ISSUE THREAD

**Issue by TMFuzz** [Kieaer/Essentials#18]
C:\Users\Skate\Desktop\New folder\mindustry-server>java -jar server.jar
Failed to load mod file config/mods/Essentials.jar. Skipping.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at io.anuke.mindustry.mod.Mods.loadMod(Mods.java:520)
        at io.anuke.mindustry.mod.Mods.load(Mods.java:180)
        at io.anuke.mindustry.Vars.init(Vars.java:267)
        at io.anuke.mindustry.server.MindustryServer.init(MindustryServer.java:35)
        at io.anuke.arc.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:76)
        at io.anuke.arc.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:64)
Caused by: io.anuke.arc.util.ArcRuntimeException: File not found: config\mods\Essentials\data\data.json (Local)
        at io.anuke.arc.files.FileHandle.read(FileHandle.java:191)
        at io.anuke.arc.files.FileHandle.readString(FileHandle.java:273)
        at io.anuke.arc.files.FileHandle.readString(FileHandle.java:258)
        at essentials.utils.Config.main(Config.java:289)
        at essentials.Main.<init>(Main.java:77)
        ... 10 more

**Comment by Kieaer** [comment]
Delete all data folder and use beta v2 build.
