### ISSUE TITLE
File not found, skipping mod.

### ISSUE THREAD

**Issue by TMFuzz** [Kieaer/Essentials#27]
fresh server and fresh mod download produced this issue.
```
C:\Users\Skate\Desktop\game server stuff\mindustry-server>java -jar server.jar
[Essential] The plugin file or folder path is invalid. Please check your server path!
Failed to load mod file config/mods/Essentials.jar. Skipping.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at io.anuke.mindustry.mod.Mods.loadMod(Mods.java:529)
        at io.anuke.mindustry.mod.Mods.load(Mods.java:180)
        at io.anuke.mindustry.Vars.init(Vars.java:267)
        at io.anuke.mindustry.server.MindustryServer.init(MindustryServer.java:35)
        at io.anuke.arc.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:76)
        at io.anuke.arc.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:64)
Caused by: io.anuke.arc.util.ArcRuntimeException: File not found: config\mods\Essentials\data\data.json (Local)
        at io.anuke.arc.files.FileHandle.read(FileHandle.java:191)
        at io.anuke.arc.files.FileHandle.readString(FileHandle.java:273)
        at io.anuke.arc.files.FileHandle.readString(FileHandle.java:258)
        at essentials.utils.Config.main(Config.java:344)
        at essentials.Main.<init>(Main.java:84)
        ... 10 more

[12-10-2019 | 13:11:57] [INFO] Server loaded. Type 'help' for help.
>
```

**Comment by Kieaer** [comment]
Contains a spaces in the your server folder path.

**Comment by TMFuzz** [comment]
oh, yeah that fixed it.

**Comment by Kieaer** [comment]
This's a folder path bug.

**Comment by TMFuzz** [comment]
Yay something helpful.
