### ISSUE TITLE
Server b100 crash when under-level player tries to build hi-exp building

### ISSUE THREAD

**Issue by Remint32** [Kieaer/Essentials#28]
```
> java.lang.NumberFormatException: For input string: "null"
    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.base/java.lang.Integer.parseInt(Integer.java:652)
    at java.base/java.lang.Integer.parseInt(Integer.java:770)
    at essentials.core.EPG.lambda$main$0(EPG.java:32)
    at io.anuke.arc.Events.lambda$fire$2(Events.java:26)
    at io.anuke.arc.collection.Array.each(Array.java:171)
    at io.anuke.arc.Events.fire(Events.java:26)
    at io.anuke.arc.Events.fire(Events.java:21)
    at io.anuke.mindustry.entities.traits.BuilderTrait.lambda$updateBuilding$1(BuilderTrait.java:79)
    at io.anuke.arc.backends.headless.HeadlessApplication.executeRunnables(HeadlessApplication.java:126)
    at io.anuke.arc.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:95)
    at io.anuke.arc.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:64)
[12-11-2019 \| 08:47:57] [INFO] Sending crash report.
[12-11-2019 \| 08:47:57] [INFO] Crash sent successfully.
```

**Comment by Remint32** [comment]
Configs: 

[configs.zip](https://github.com/Kieaer/Essentials/files/3948676/configs.zip)

**Comment by Remint32** [comment]
I found out that this happens when an under-level player tries to build a building that requires more experience
