### ISSUE TITLE
crash: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by mayli** [Kieaer/Essentials#3]
```
$ jre1.8.0_221/bin/java -jar server.jar
java.lang.NoClassDefFoundError: io/anuke/mindustry/game/EventType$PlayerJoin
        at essential.Essentials.<init>(Essentials.java:28)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at io.anuke.mindustry.plugin.Plugins.loadPlugin(Plugins.java:55)
        at io.anuke.mindustry.plugin.Plugins.load(Plugins.java:22)
        at io.anuke.mindustry.server.ServerControl.<init>(ServerControl.java:114)
        at io.anuke.mindustry.server.MindustryServer.init(MindustryServer.java:29)
        at io.anuke.arc.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:76)
        at io.anuke.arc.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:64)
Caused by: java.lang.ClassNotFoundException: io.anuke.mindustry.game.EventType$PlayerJoin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 12 more
```

**Comment by Kieaer** [comment]
Fixed https://github.com/Kieaer/Essentials/commit/3802c9e282fa40bd514658a4fa991705a9beaea0
