### ISSUE TITLE
Server b101.1 crash on startup

### ISSUE THREAD

**Issue by Remint32** [Kieaer/Essentials#38]
```

> mindustry@v106011:~/mainservervanilla$ java -jar server-release-b101.1.jar
[12-19-2019 \| 00:08:27] [E] Failed to load mod file config/mods/Essentials.jar. Skipping.
[12-19-2019 \| 00:08:27] [E] java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at io.anuke.mindustry.mod.Mods.loadMod(Mods.java:632)
    at io.anuke.mindustry.mod.Mods.load(Mods.java:233)
    at io.anuke.mindustry.Vars.init(Vars.java:274)
    at io.anuke.mindustry.server.ServerLauncher.init(ServerLauncher.java:58)
    at io.anuke.arc.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:75)
    at io.anuke.arc.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:63)
Caused by: java.lang.NoSuchMethodError: 'io.anuke.arc.files.FileHandle io.anuke.arc.Settings.getDataDirectory()'
    at essentials.utils.Config.(Config.java:33)
    at essentials.Main.(Main.java:74)
    ... 10 more
[12-19-2019 \| 00:08:28] [I] Server loaded. Type 'help' for help.
>
```

**Comment by Remint32** [comment]
Server b101.1
Plugin 6.1.1

**Comment by Kieaer** [comment]
https://github.com/Kieaer/Essentials/commit/305db0c2c189965b44653b31d5def2f461c04dc7
