### ISSUE TITLE
Server b100 crash

### ISSUE THREAD

**Issue by Remint32** [Kieaer/Essentials#39]
```
io.anuke.arc.util.ArcRuntimeException: File not found: config/mods/Essentials/BlockReqExp.txt (Local)
    at io.anuke.arc.files.FileHandle.read(FileHandle.java:191)
    at io.anuke.arc.files.FileHandle.readString(FileHandle.java:273)
    at io.anuke.arc.files.FileHandle.readString(FileHandle.java:258)
    at essentials.core.EPG.lambda$main$0(EPG.java:29)
    at io.anuke.arc.Events.lambda$fire$2(Events.java:26)
    at io.anuke.arc.collection.Array.each(Array.java:171)
    at io.anuke.arc.Events.fire(Events.java:26)
    at io.anuke.arc.Events.fire(Events.java:21)
    at io.anuke.mindustry.entities.traits.BuilderTrait.lambda$updateBuilding$0(BuilderTrait.java:80)
    at io.anuke.arc.backends.headless.HeadlessApplication.executeRunnables(HeadlessApplication.java:126)
    at io.anuke.arc.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:95)
    at io.anuke.arc.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:64)
[12-19-2019 | 00:41:32] [I] Sending crash report.
[12-19-2019 | 00:41:32] [I] Crash sent successfully.
```

**Comment by Remint32** [comment]
**_BlockReqExp.txt_**
:thinking:
