### ISSUE TITLE
Anti-grief system not working

### ISSUE THREAD

**Issue by LunarstarFurry** [Kieaer/Essentials#41]
When I try to connect to event server Just Connection lost or timeout

**Comment by Kieaer** [comment]
It's port bug

**Comment by LunarstarFurry** [comment]
Sooooo fix in future?

**Comment by Kieaer** [comment]
@LuxarstarPony I will fix it no matter what today.

**Comment by LunarstarFurry** [comment]
Okie Dokie~~~~ Thanks~

**Comment by LunarstarFurry** [comment]
Ohhhhhh BTW Can I stop the event? I only see host join but no stop

**Comment by LunarstarFurry** [comment]
And AntiRush,RealName and Auto difficult keep switching back to false by it self for some reason

**Comment by Kieaer** [comment]
This operation is delayed due to large internal structural changes.

**Comment by LunarstarFurry** [comment]
Oh okay so AntiRush doesn't work now?

**Comment by Kieaer** [comment]
@LunarstarPony Yes

**Comment by LunarstarFurry** [comment]
Okie Dokie

**Comment by Kieaer** [comment]
@LunarstarPony Event server is now working but anti rush/grief/detct isn't working now
Check 7.0 version

**Comment by LunarstarFurry** [comment]
Nope

**Comment by LunarstarFurry** [comment]
[12-31-2019 | 22:41:44] [I] <LunarstarPony: /event host Lunarstar Veins pvp>
[12-31-2019 | 22:41:51] [I] [Essential] LunarstarPony Player has opened event server on port 19.
[12-31-2019 | 22:41:51] [I] [dXhbC+r8BYc=] LunarstarPony has disconnected. (closed)
[12-31-2019 | 22:42:03] [I] [dXhbC+r8BYc=] LunarstarPony has connected. 
[12-31-2019 | 22:42:15] [I] <LunarstarPony: /event join Lunarstar>
Exception in thread "Thread-1927" java.lang.ArrayIndexOutOfBoundsException: 2
        at essentials.Main.lambda$registerClientCommands$50(Main.java:1533)
        at java.lang.Thread.run(Thread.java:748)

**Comment by LunarstarFurry** [comment]
Same Error when trying to join

**Comment by LunarstarFurry** [comment]
Failed to read remote method 'SendChat Message'

**Comment by Kieaer** [comment]
@LunarstarPony still working
