### ISSUE TITLE
NullPointerExceptions

### ISSUE THREAD

**Issue by Kieaer** [Kieaer/Essentials#44]
java.lang.RuntimeException: Failed to to read remote method 'sendChatMessage'!
        at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:119)
        at mindustry.core.NetServer.lambda$new$5(NetServer.java:232)
        at mindustry.net.Net.handleServerReceived(Net.java:266)
        at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:115)
        at arc.backend.headless.HeadlessApplication.executeRunnables(HeadlessApplication.java:120)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:89)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:63)
Caused by: java.lang.NullPointerException
        at essentials.core.Translate.main(Translate.java:25)
        at essentials.Main.lambda$new$13(Main.java:517)
        at arc.Events.lambda$fire$2(Events.java:26)
        at arc.struct.Array.each(Array.java:171)
        at arc.Events.fire(Events.java:26)
        at arc.Events.fire(Events.java:21)
        at mindustry.core.NetClient.sendChatMessage(NetClient.java:201)
        at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:117)
        ... 6 more

**Comment by Kieaer** [comment]
https://github.com/Kieaer/Essentials/blob/master/src/main/java/essentials/Threads.java#L1169
