### ISSUE TITLE
Can't load player data information

### ISSUE THREAD

**Issue by LunarstarFurry** [Kieaer/Essentials#54]
Exception in thread "LunarstarPony Player Join thread" java.lang.NullPointerException
        at essentials.feature.Permission.isAdmin(Permission.java:62)
        at essentials.core.player.PlayerCore.load(PlayerCore.java:44)
        at essentials.internal.Event.lambda$new$9(Event.java:272)
        at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: Failed to to read remote method 'sendChatMessage'!
        at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:119)
        at mindustry.core.NetServer.lambda$new$5(NetServer.java:251)
        at mindustry.net.Net.handleServerReceived(Net.java:266)
        at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:115)
        at arc.backend.headless.HeadlessApplication.executeRunnables(HeadlessApplication.java:120)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:89)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:63)
Caused by: java.lang.NullPointerException
        at essentials.internal.Event.lambda$new$13(Event.java:358)
        at arc.Events.lambda$fire$2(Events.java:26)
        at arc.struct.Array.each(Array.java:181)
        at arc.Events.fire(Events.java:26)
        at arc.Events.fire(Events.java:21)
        at mindustry.core.NetClient.sendChatMessage(NetClient.java:166)
        at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:117)
        ... 6 more

**Comment by Kieaer** [comment]
This error was not logged on my error report server.
It will take time to solve.

**Comment by Kieaer** [comment]
https://github.com/Kieaer/Essentials/commit/d896fa6d5d32ddbfcabe9d9056439c5c7542bd52
