### ISSUE TITLE
Failed to load 

### ISSUE THREAD

**Issue by LunarstarFurry** [Kieaer/Essentials#56]
Running CentOS 7
Java tried both 8 and 11

[05-09-2020 | 12:13:58] [I] Config file updated!
[05-09-2020 | 12:13:58] [I] Plugin language: 
[05-09-2020 | 12:13:58] [E] Failed to load mod file config/mods/Essentials.jar. Skipping.
[05-09-2020 | 12:13:58] [E] java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at mindustry.mod.Mods.loadMod(Mods.java:650)
        at mindustry.mod.Mods.load(Mods.java:247)
        at mindustry.Vars.init(Vars.java:275)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:58)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:75)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:63)
Caused by: java.lang.NoClassDefFoundError: org/h2/upgrade/DbUpgrade
        at org.h2.Driver.connect(Driver.java:65)
        at essentials.external.DriverLoader.connect(DriverLoader.java:152)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at essentials.core.player.Database.connect(Database.java:80)
        at essentials.Main.<init>(Main.java:157)
        ... 10 more
Caused by: java.lang.ClassNotFoundException: org.h2.upgrade.DbUpgrade
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 16 more

**Comment by LunarstarFurry** [comment]
I tried and It works on my Windows PC tho

**Comment by Kieaer** [comment]
Please check file exists in ``config/mods/Essentials/Driver/h2-1.4.200.jar``

**Comment by LunarstarFurry** [comment]
Yup It's there

**Comment by Kieaer** [comment]
Solved in Essentials 10
