### ISSUE TITLE
Server doesn't start

### ISSUE THREAD

**Issue by Xasmedy** [Kieaer/Essentials#79]
**Describe the bug**
Time I do the command for start the server, the console stuck. (Seems like the plugin isn't able to load)
Naturaly I've removed every other plugin for check if essentials is the cause and unfortunately yes.

**Screenshots**
Nothing to show just a stuck console https://prnt.sc/w76zsj.

**Server (please complete the following information):**
 O.S.: Windows 10 64Bit, Server version: 121.4, Essentials version: 11.6

**Comment by Kieaer** [comment]
@Xasmedy @RebornTrack970

To check the problem, you need to check what causes the server to stop.
# Follow on this step
1. Go to visualVM homepage - https://visualvm.github.io/
![image](https://user-images.githubusercontent.com/44261958/102893608-38e8b700-44a5-11eb-9552-47d2e1d12cc7.png)

2. Download standalone -> ``visualVM 2.0.5.zip``
![image](https://user-images.githubusercontent.com/44261958/102893592-32f2d600-44a5-11eb-96f6-1a11b1acee20.png)

3. Unzip ``visualVM 2.0.5.zip`` and execute ``bin/visualvm.exe``
![image](https://user-images.githubusercontent.com/44261958/102893702-60d81a80-44a5-11eb-815c-545914d29f84.png)

4. If the server is running, it will appear as below. Click on it.
![image](https://user-images.githubusercontent.com/44261958/102893819-86652400-44a5-11eb-9645-821c6f5db81c.png)

5. Go to ``Threads`` tab and click ``Thread dump`` button.
![image](https://user-images.githubusercontent.com/44261958/102894381-59654100-44a6-11eb-9c46-f3858a6dde44.png)

6. If you can see this texts, you're done.
![image](https://user-images.githubusercontent.com/44261958/102894452-7863d300-44a6-11eb-9226-a0cde7c1d49b.png)

Copy all texts and upload here.

**Comment by Xasmedy** [comment]
```
2020-12-22 14:56:36
Full thread dump Java HotSpot(TM) 64-Bit Server VM (14.0.2+12-46 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x0000021af5d738a0, length=17, elements={
0x0000021af48b9000, 0x0000021af48ba000, 0x0000021af515a000, 0x0000021af515b000,
0x0000021af515c000, 0x0000021af5165000, 0x0000021af516d800, 0x0000021af5170800,
0x0000021af52a9800, 0x0000021af52b7800, 0x0000021af5a21000, 0x0000021ad06be000,
0x0000021af5a03800, 0x0000021af5f8f000, 0x0000021af60f3000, 0x0000021af5cfd000,
0x0000021af625e000
}

"Reference Handler" #2 daemon prio=10 os_prio=2 cpu=0.00ms elapsed=44.02s tid=0x0000021af48b9000 nid=0x1126c waiting on condition  [0x000000c11eafe000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@14.0.2/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@14.0.2/Reference.java:241)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@14.0.2/Reference.java:213)

   Locked ownable synchronizers:
        - None

"Finalizer" #3 daemon prio=8 os_prio=1 cpu=0.00ms elapsed=44.02s tid=0x0000021af48ba000 nid=0xb764 in Object.wait()  [0x000000c11ebfe000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@14.0.2/Native Method)
        - waiting on <0x0000000701700458> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@14.0.2/ReferenceQueue.java:155)
        - locked <0x0000000701700458> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@14.0.2/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@14.0.2/Finalizer.java:170)

   Locked ownable synchronizers:
        - None

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 cpu=0.00ms elapsed=44.01s tid=0x0000021af515a000 nid=0xeba8 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Attach Listener" #5 daemon prio=5 os_prio=2 cpu=140.63ms elapsed=44.01s tid=0x0000021af515b000 nid=0xb730 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Service Thread" #6 daemon prio=9 os_prio=0 cpu=0.00ms elapsed=44.01s tid=0x0000021af515c000 nid=0xbba8 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread0" #7 daemon prio=9 os_prio=2 cpu=453.13ms elapsed=44.01s tid=0x0000021af5165000 nid=0x1000c waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
        - None

"C1 CompilerThread0" #10 daemon prio=9 os_prio=2 cpu=343.75ms elapsed=44.01s tid=0x0000021af516d800 nid=0x113c8 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
        - None

"Sweeper thread" #11 daemon prio=9 os_prio=2 cpu=0.00ms elapsed=44.01s tid=0x0000021af5170800 nid=0x10c28 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Notification Thread" #12 daemon prio=9 os_prio=0 cpu=0.00ms elapsed=44.00s tid=0x0000021af52a9800 nid=0xb984 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Common-Cleaner" #13 daemon prio=8 os_prio=1 cpu=0.00ms elapsed=43.99s tid=0x0000021af52b7800 nid=0xda30 in Object.wait()  [0x000000c11f4fe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@14.0.2/Native Method)
        - waiting on <0x00000007017013f0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@14.0.2/ReferenceQueue.java:155)
        - locked <0x00000007017013f0> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@14.0.2/CleanerImpl.java:148)
        at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)
        at jdk.internal.misc.InnocuousThread.run(java.base@14.0.2/InnocuousThread.java:134)

   Locked ownable synchronizers:
        - None

"HeadlessApplication" #14 prio=5 os_prio=0 cpu=42734.38ms elapsed=43.87s tid=0x0000021af5a21000 nid=0x10650 runnable  [0x000000c11f6fc000]
   java.lang.Thread.State: RUNNABLE
        at java.util.ResourceBundle.checkList(java.base@14.0.2/ResourceBundle.java:1710)
        at java.util.ResourceBundle.getBundleImpl(java.base@14.0.2/ResourceBundle.java:1658)
        at java.util.ResourceBundle.getBundleImpl(java.base@14.0.2/ResourceBundle.java:1593)
        at java.util.ResourceBundle.getBundleImpl(java.base@14.0.2/ResourceBundle.java:1556)
        at java.util.ResourceBundle.getBundle(java.base@14.0.2/ResourceBundle.java:1066)
        at essentials.internal.Bundle.<init>(Bundle.kt:24)
        at essentials.Config.<clinit>(Config.kt:18)
        at essentials.Main.<init>(Main.kt:52)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@14.0.2/Native Method)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@14.0.2/NativeConstructorAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@14.0.2/DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstanceWithCaller(java.base@14.0.2/Constructor.java:500)
        at java.lang.reflect.Constructor.newInstance(java.base@14.0.2/Constructor.java:481)
        at mindustry.mod.Mods.loadMod(Mods.java:640)
        at mindustry.mod.Mods.load(Mods.java:246)
        at mindustry.Vars.init(Vars.java:283)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:57)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:66)
        - locked <0x0000000701760810> (a arc.struct.Seq)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)

   Locked ownable synchronizers:
        - None

"DestroyJavaVM" #15 prio=5 os_prio=0 cpu=140.63ms elapsed=43.87s tid=0x0000021ad06be000 nid=0x9358 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Timer-0" #16 prio=5 os_prio=0 cpu=0.00ms elapsed=43.11s tid=0x0000021af5a03800 nid=0x3608 in Object.wait()  [0x000000c11f5ff000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@14.0.2/Native Method)
        - waiting on <0x00000007019c5988> (a java.util.TaskQueue)
        at java.lang.Object.wait(java.base@14.0.2/Object.java:321)
        at java.util.TimerThread.mainLoop(java.base@14.0.2/Timer.java:527)
        - locked <0x00000007019c5988> (a java.util.TaskQueue)
        at java.util.TimerThread.run(java.base@14.0.2/Timer.java:506)

   Locked ownable synchronizers:
        - None

"RMI TCP Accept-0" #18 daemon prio=5 os_prio=0 cpu=15.63ms elapsed=23.80s tid=0x0000021af5f8f000 nid=0xfc18 runnable  [0x000000c11f7fe000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.Net.accept(java.base@14.0.2/Native Method)
        at sun.nio.ch.NioSocketImpl.accept(java.base@14.0.2/NioSocketImpl.java:755)
        at java.net.ServerSocket.implAccept(java.base@14.0.2/ServerSocket.java:684)
        at java.net.ServerSocket.platformImplAccept(java.base@14.0.2/ServerSocket.java:650)
        at java.net.ServerSocket.implAccept(java.base@14.0.2/ServerSocket.java:626)
        at java.net.ServerSocket.implAccept(java.base@14.0.2/ServerSocket.java:583)
        at java.net.ServerSocket.accept(java.base@14.0.2/ServerSocket.java:540)
        at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(jdk.management.agent@14.0.2/LocalRMIServerSocketFactory.java:52)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(java.rmi@14.0.2/TCPTransport.java:413)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(java.rmi@14.0.2/TCPTransport.java:377)
        at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

   Locked ownable synchronizers:
        - <0x0000000701bdc0f8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"RMI TCP Connection(1)-192.168.56.1" #19 daemon prio=5 os_prio=0 cpu=109.38ms elapsed=23.76s tid=0x0000021af60f3000 nid=0x3aac runnable  [0x000000c11fdfe000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.Net.poll(java.base@14.0.2/Native Method)
        at sun.nio.ch.NioSocketImpl.park(java.base@14.0.2/NioSocketImpl.java:181)
        at sun.nio.ch.NioSocketImpl.timedRead(java.base@14.0.2/NioSocketImpl.java:285)
        at sun.nio.ch.NioSocketImpl.implRead(java.base@14.0.2/NioSocketImpl.java:309)
        at sun.nio.ch.NioSocketImpl.read(java.base@14.0.2/NioSocketImpl.java:350)
        at sun.nio.ch.NioSocketImpl$1.read(java.base@14.0.2/NioSocketImpl.java:803)
        at java.net.Socket$SocketInputStream.read(java.base@14.0.2/Socket.java:982)
        at java.io.BufferedInputStream.fill(java.base@14.0.2/BufferedInputStream.java:244)
        at java.io.BufferedInputStream.read(java.base@14.0.2/BufferedInputStream.java:263)
        - locked <0x0000000701b9d2b8> (a java.io.BufferedInputStream)
        at java.io.FilterInputStream.read(java.base@14.0.2/FilterInputStream.java:82)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(java.rmi@14.0.2/TCPTransport.java:569)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(java.rmi@14.0.2/TCPTransport.java:828)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(java.rmi@14.0.2/TCPTransport.java:705)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$148/0x0000000800cd0840.run(java.rmi@14.0.2/Unknown Source)
        at java.security.AccessController.executePrivileged(java.base@14.0.2/AccessController.java:753)
        at java.security.AccessController.doPrivileged(java.base@14.0.2/AccessController.java:391)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(java.rmi@14.0.2/TCPTransport.java:704)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@14.0.2/ThreadPoolExecutor.java:1130)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@14.0.2/ThreadPoolExecutor.java:630)
        at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

   Locked ownable synchronizers:
        - <0x0000000701b9d6b8> (a java.util.concurrent.ThreadPoolExecutor$Worker)
        - <0x0000000701bcf1e8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"RMI Scheduler(0)" #20 daemon prio=5 os_prio=0 cpu=0.00ms elapsed=23.75s tid=0x0000021af5cfd000 nid=0x112e8 waiting on condition  [0x000000c11fefe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@14.0.2/Native Method)
        - parking to wait for  <0x0000000701b9e100> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@14.0.2/LockSupport.java:252)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@14.0.2/AbstractQueuedSynchronizer.java:1661)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@14.0.2/ScheduledThreadPoolExecutor.java:1182)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@14.0.2/ScheduledThreadPoolExecutor.java:899)
        at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@14.0.2/ThreadPoolExecutor.java:1056)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@14.0.2/ThreadPoolExecutor.java:1116)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@14.0.2/ThreadPoolExecutor.java:630)
        at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

   Locked ownable synchronizers:
        - None

"JMX server connection timeout 21" #21 daemon prio=5 os_prio=0 cpu=15.63ms elapsed=23.74s tid=0x0000021af625e000 nid=0x102cc in Object.wait()  [0x000000c11fffe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@14.0.2/Native Method)
        - waiting on <0x0000000701b9f0c8> (a [I)
        at com.sun.jmx.remote.internal.ServerCommunicatorAdmin$Timeout.run(java.management@14.0.2/ServerCommunicatorAdmin.java:171)
        - locked <0x0000000701b9f0c8> (a [I)
        at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

   Locked ownable synchronizers:
        - None

"VM Thread" os_prio=2 cpu=46.88ms elapsed=44.02s tid=0x0000021af48b6000 nid=0xe4a8 runnable  

"GC Thread#0" os_prio=2 cpu=109.38ms elapsed=44.02s tid=0x0000021ad0726800 nid=0xf854 runnable  

"GC Thread#1" os_prio=2 cpu=93.75ms elapsed=43.70s tid=0x0000021af5e29000 nid=0x10900 runnable  

"GC Thread#2" os_prio=2 cpu=109.38ms elapsed=43.70s tid=0x0000021af5d7e800 nid=0xe5dc runnable  

"GC Thread#3" os_prio=2 cpu=109.38ms elapsed=43.70s tid=0x0000021af5ca8000 nid=0xb03c runnable  

"GC Thread#4" os_prio=2 cpu=109.38ms elapsed=43.70s tid=0x0000021af5c63000 nid=0x113f0 runnable  

"GC Thread#5" os_prio=2 cpu=109.38ms elapsed=43.70s tid=0x0000021af5c5f800 nid=0xdbc4 runnable  

"G1 Main Marker" os_prio=2 cpu=0.00ms elapsed=44.02s tid=0x0000021ad0749800 nid=0xc5b4 runnable  

"G1 Conc#0" os_prio=2 cpu=0.00ms elapsed=44.02s tid=0x0000021ad074c000 nid=0xdc08 runnable  

"G1 Refine#0" os_prio=2 cpu=0.00ms elapsed=44.02s tid=0x0000021af47a7800 nid=0x108d8 runnable  

"G1 Young RemSet Sampling" os_prio=2 cpu=0.00ms elapsed=44.02s tid=0x0000021af47a9000 nid=0x10ccc runnable  
"VM Periodic Task Thread" os_prio=2 cpu=0.00ms elapsed=44.00s tid=0x0000021af52aa800 nid=0xcc20 waiting on condition  

JNI global refs: 25, weak refs: 0

```
