### ISSUE TITLE
SQL errors

### ISSUE THREAD

**Issue by notAreYouScared** [Kieaer/Essentials#8]
With the latest version, it complains about the player table not existing. 

org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: players)
at org.sqlite.core.DB.newSQLException(DB.java:941)
at org.sqlite.core.DB.newSQLException(DB.java:953)
at org.sqlite.core.DB.throwex(DB.java:918)
at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
at org.sqlite.core.DB.prepare(DB.java:257)
at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
at essentials.EssentialPlayer.getData(EssentialPlayer.java:181)
at essentials.EssentialLog.lambda$main$5(EssentialLog.java:112)
at io.anuke.arc.Events.lambda$fire$2(Events.java:26)
at io.anuke.arc.collection.Array.each(Array.java:174)
at io.anuke.arc.Events.fire(Events.java:26)
at io.anuke.arc.Events.fire(Events.java:21)
at io.anuke.mindustry.core.NetServer.connectConfirm(NetServer.java:551)
at io.anuke.mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:13)
at io.anuke.mindustry.core.NetServer.lambda$new$3(NetServer.java:197)
at io.anuke.mindustry.net.Net.handleServerReceived(Net.java:265)
at io.anuke.mindustry.net.ArcNetImpl$2.lambda$received$2(ArcNetImpl.java:115)
at io.anuke.arc.backends.headless.HeadlessApplication.executeRunnables(HeadlessApplication.java:126)
at io.anuke.arc.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:95)
at io.anuke.arc.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:64)

**Comment by Kieaer** [comment]
fixed https://github.com/Kieaer/Essentials/commit/86722dbc4be21f4f8057107496cbe131e85657bd
