### ISSUE TITLE
Error i get all the time

### ISSUE THREAD

**Issue by posiblyLopsided** [Kieaer/Essentials#80]
I thnk i get this error whenever a game ends

java.lang.NullPointerException: Cannot invoke "mindustry.gen.Player.uuid()" because "player" is null
    at essentials.features.Event$register$4.get(Event.kt:128)
    at essentials.features.Event$register$4.get(Event.kt:36)
    at arc.Events.lambda$fire$2(Events.java:30)
    at arc.struct.Seq.each(Seq.java:200)
    at arc.Events.fire(Events.java:30)
    at arc.Events.fire(Events.java:25)
    at mindustry.core.Logic.checkGameState(Logic.java:250)
    at mindustry.core.Logic.update(Logic.java:414)
    at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:89)
    at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)

It happens pretty frequently and crashes entire server

**Comment by Kieaer** [comment]
Use bug fixed version (11.7)
