### ISSUE TITLE
Another server crashing bug.  Not for sure the cause

### ISSUE THREAD

**Issue by posiblyLopsided** [Kieaer/Essentials#81]
Constantly get this bug and crashes server

`java.lang.NullPointerException: Cannot read field "block" because the return value of "mindustry.gen.Unit.buildPlan()" is null
    at essentials.features.Event$register$11.get(Event.kt:356)
    at essentials.features.Event$register$11.get(Event.kt:36)
    at arc.Events.lambda$fire$2(Events.java:30)
    at arc.struct.Seq.each(Seq.java:200)
    at arc.Events.fire(Events.java:30)
    at arc.Events.fire(Events.java:25)
    at mindustry.world.blocks.ConstructBlock.constructed(ConstructBlock.java:125)
    at mindustry.world.blocks.ConstructBlock$ConstructBuild.construct(ConstructBlock.java:251)
    at mindustry.gen.UnitEntityLegacyPoly.update(UnitEntityLegacyPoly.java:1496)
    at mindustry.entities.EntityGroup.each(EntityGroup.java:68)
    at mindustry.entities.EntityGroup.update(EntityGroup.java:58)
    at mindustry.gen.Groups.update(Groups.java:71)
    at mindustry.core.Logic.update(Logic.java:410)
    at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:89)
    at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)`

**Comment by posLop** [comment]
I believe that it may have something to do with using polys in a squad and switching teams while building
